### PR TITLE
Add SCSS output

### PR DESCRIPTION
**Pull request by ztlhayden**
This was a super helpful little program but I mostly use sass; so I used it as a chance to practice Py!

I updated it with an argument to change the format to scss.

### CODE REVIEW

**Comment by rensbaardman** [comment]
Hey, great that you found this utility and thanks for the scss-addition :)

I'd like to merge it, but I have two comments:

- I prefer css to be the default, even without setting it on the command line. (so `python ase-to-css.py swatches.ase` should also work)
- I think the following CLI-syntax is more common: `python ase-to-css.py -s scss swatches.ase` or `python ase-to-css.py --style scss swatches.ase`.

Would you be able to add those changes? You might want to use something like `argparse` for that.

Apart from that, looks great - especially if you're just starting out with Python 😊

**Comment by ztlhayden** [comment]
Thank you so so much for the help. Your idea sent me down the right path and with some youtube and bourbon I think I've got it running. I agree it's much cleaner this way. This little tool helped me out when I needed it and taught me alot!

I'm happy to hear any input you have on what I've written and hopefully others will find this as useful as I have.

**Comment by ztlhayden** [comment]
Any chance we can get this merged or is there anything I should fix?

**Comment by rensbaardman** [comment]
It looks good! Thanks a lot for implementing the argparse-stuff. My apologies for the late answer, had a busy month.

Thanks for your contributions, it really improves the project! :)

**Pull request merged**
